//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub type AddPlayer {
  AddPlayer(id: String, name: Option(String))
}

pub fn add_player(id id: String, name name: Option(String)) {
  let sql =
    "INSERT INTO players (
	id, name 
) VALUES (
	?, ?
)
RETURNING id, name"
  #(
    sql,
    [
      dev.ParamString(id),
      dev.ParamNullable(option.map(name, fn(v) { dev.ParamString(v) })),
    ],
    add_player_decoder(),
  )
}

pub fn add_player_decoder() -> decode.Decoder(AddPlayer) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.optional(decode.string))
  decode.success(AddPlayer(id:, name:))
}

pub type GetPlayer {
  GetPlayer(id: String, name: Option(String))
}

pub fn get_player(id id: String) {
  let sql =
    "SELECT id, name FROM players
WHERE id = ?"
  #(sql, [dev.ParamString(id)], get_player_decoder())
}

pub fn get_player_decoder() -> decode.Decoder(GetPlayer) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.optional(decode.string))
  decode.success(GetPlayer(id:, name:))
}

pub type UpdatePlayer {
  UpdatePlayer(id: String, name: Option(String))
}

pub fn update_player(name name: Option(String), id id: String) {
  let sql =
    "UPDATE players
SET name = ?
WHERE id = ?
RETURNING id, name"
  #(
    sql,
    [
      dev.ParamNullable(option.map(name, fn(v) { dev.ParamString(v) })),
      dev.ParamString(id),
    ],
    update_player_decoder(),
  )
}

pub fn update_player_decoder() -> decode.Decoder(UpdatePlayer) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.optional(decode.string))
  decode.success(UpdatePlayer(id:, name:))
}

pub type AddGame {
  AddGame(id: String, code: String, status: String)
}

pub fn add_game(id id: String, code code: String, status status: String) {
  let sql =
    "INSERT INTO games (
	id, code, status 
) VALUES (
	?, ?, ?
)
RETURNING id, code, status"
  #(
    sql,
    [dev.ParamString(id), dev.ParamString(code), dev.ParamString(status)],
    add_game_decoder(),
  )
}

pub fn add_game_decoder() -> decode.Decoder(AddGame) {
  use id <- decode.field(0, decode.string)
  use code <- decode.field(1, decode.string)
  use status <- decode.field(2, decode.string)
  decode.success(AddGame(id:, code:, status:))
}

pub type GetGames {
  GetGames(id: String, code: String, status: String)
}

pub fn get_games() {
  let sql = "SELECT id, code, status FROM games"
  #(sql, [], get_games_decoder())
}

pub fn get_games_decoder() -> decode.Decoder(GetGames) {
  use id <- decode.field(0, decode.string)
  use code <- decode.field(1, decode.string)
  use status <- decode.field(2, decode.string)
  decode.success(GetGames(id:, code:, status:))
}

pub type GetGameWithCode {
  GetGameWithCode(id: String, code: String, status: String)
}

pub fn get_game_with_code(code code: String) {
  let sql =
    "SELECT id, code, status FROM games
WHERE code = ?"
  #(sql, [dev.ParamString(code)], get_game_with_code_decoder())
}

pub fn get_game_with_code_decoder() -> decode.Decoder(GetGameWithCode) {
  use id <- decode.field(0, decode.string)
  use code <- decode.field(1, decode.string)
  use status <- decode.field(2, decode.string)
  decode.success(GetGameWithCode(id:, code:, status:))
}

pub type UpdateGame {
  UpdateGame(id: String, code: String, status: String)
}

pub fn update_game(status status: String, id id: String) {
  let sql =
    "UPDATE games
SET status = ?
WHERE id = ?
RETURNING id, code, status"
  #(sql, [dev.ParamString(status), dev.ParamString(id)], update_game_decoder())
}

pub fn update_game_decoder() -> decode.Decoder(UpdateGame) {
  use id <- decode.field(0, decode.string)
  use code <- decode.field(1, decode.string)
  use status <- decode.field(2, decode.string)
  decode.success(UpdateGame(id:, code:, status:))
}

pub type AddPlayerGame {
  AddPlayerGame(
    id: String,
    player_id: String,
    game_id: String,
    joined: Int,
    ready: Bool,
    red: Int,
    yellow: Int,
    green: Int,
    blue: Int,
    missed: Int,
  )
}

pub fn add_player_game(
  id id: String,
  player_id player_id: String,
  game_id game_id: String,
  joined joined: Int,
  ready ready: Bool,
  red red: Int,
  yellow yellow: Int,
  green green: Int,
  blue blue: Int,
  missed missed: Int,
) {
  let sql =
    "INSERT INTO player_games (
	id, player_id, game_id, joined, ready, red, yellow, green, blue, missed
) VALUES (
	?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, player_id, game_id, joined, ready, red, yellow, green, blue, missed"
  #(
    sql,
    [
      dev.ParamString(id),
      dev.ParamString(player_id),
      dev.ParamString(game_id),
      dev.ParamInt(joined),
      dev.ParamBool(ready),
      dev.ParamInt(red),
      dev.ParamInt(yellow),
      dev.ParamInt(green),
      dev.ParamInt(blue),
      dev.ParamInt(missed),
    ],
    add_player_game_decoder(),
  )
}

pub fn add_player_game_decoder() -> decode.Decoder(AddPlayerGame) {
  use id <- decode.field(0, decode.string)
  use player_id <- decode.field(1, decode.string)
  use game_id <- decode.field(2, decode.string)
  use joined <- decode.field(3, decode.int)
  use ready <- decode.field(4, dev.bool_decoder())
  use red <- decode.field(5, decode.int)
  use yellow <- decode.field(6, decode.int)
  use green <- decode.field(7, decode.int)
  use blue <- decode.field(8, decode.int)
  use missed <- decode.field(9, decode.int)
  decode.success(AddPlayerGame(
    id:,
    player_id:,
    game_id:,
    joined:,
    ready:,
    red:,
    yellow:,
    green:,
    blue:,
    missed:,
  ))
}

pub type GetPlayerGame {
  GetPlayerGame(
    id: String,
    player_id: String,
    game_id: String,
    joined: Int,
    ready: Bool,
    red: Int,
    yellow: Int,
    green: Int,
    blue: Int,
    missed: Int,
  )
}

pub fn get_player_game(player_id player_id: String, code code: String) {
  let sql =
    "SELECT player_games.id, player_games.player_id, player_games.game_id, player_games.joined, player_games.ready, player_games.red, player_games.yellow, player_games.green, player_games.blue, player_games.missed FROM player_games
JOIN games ON games.id = player_games.game_id
WHERE player_games.player_id = ? AND games.code = ?"
  #(
    sql,
    [dev.ParamString(player_id), dev.ParamString(code)],
    get_player_game_decoder(),
  )
}

pub fn get_player_game_decoder() -> decode.Decoder(GetPlayerGame) {
  use id <- decode.field(0, decode.string)
  use player_id <- decode.field(1, decode.string)
  use game_id <- decode.field(2, decode.string)
  use joined <- decode.field(3, decode.int)
  use ready <- decode.field(4, dev.bool_decoder())
  use red <- decode.field(5, decode.int)
  use yellow <- decode.field(6, decode.int)
  use green <- decode.field(7, decode.int)
  use blue <- decode.field(8, decode.int)
  use missed <- decode.field(9, decode.int)
  decode.success(GetPlayerGame(
    id:,
    player_id:,
    game_id:,
    joined:,
    ready:,
    red:,
    yellow:,
    green:,
    blue:,
    missed:,
  ))
}

pub type UpdatePlayerGame {
  UpdatePlayerGame(
    id: String,
    player_id: String,
    game_id: String,
    joined: Int,
    ready: Bool,
    red: Int,
    yellow: Int,
    green: Int,
    blue: Int,
    missed: Int,
  )
}

pub fn update_player_game(
  ready ready: Bool,
  red red: Int,
  yellow yellow: Int,
  green green: Int,
  blue blue: Int,
  missed missed: Int,
  id id: String,
) {
  let sql =
    "UPDATE player_games
SET ready = ?,
red = ?,
yellow = ?,
green = ?,
blue = ?,
missed = ?
WHERE id = ?
RETURNING id, player_id, game_id, joined, ready, red, yellow, green, blue, missed"
  #(
    sql,
    [
      dev.ParamBool(ready),
      dev.ParamInt(red),
      dev.ParamInt(yellow),
      dev.ParamInt(green),
      dev.ParamInt(blue),
      dev.ParamInt(missed),
      dev.ParamString(id),
    ],
    update_player_game_decoder(),
  )
}

pub fn update_player_game_decoder() -> decode.Decoder(UpdatePlayerGame) {
  use id <- decode.field(0, decode.string)
  use player_id <- decode.field(1, decode.string)
  use game_id <- decode.field(2, decode.string)
  use joined <- decode.field(3, decode.int)
  use ready <- decode.field(4, dev.bool_decoder())
  use red <- decode.field(5, decode.int)
  use yellow <- decode.field(6, decode.int)
  use green <- decode.field(7, decode.int)
  use blue <- decode.field(8, decode.int)
  use missed <- decode.field(9, decode.int)
  decode.success(UpdatePlayerGame(
    id:,
    player_id:,
    game_id:,
    joined:,
    ready:,
    red:,
    yellow:,
    green:,
    blue:,
    missed:,
  ))
}

pub type GetPlayerGamesWithGameId {
  GetPlayerGamesWithGameId(
    id: String,
    player_id: String,
    game_id: String,
    joined: Int,
    ready: Bool,
    red: Int,
    yellow: Int,
    green: Int,
    blue: Int,
    missed: Int,
  )
}

pub fn get_player_games_with_game_id(game_id game_id: String) {
  let sql =
    "SELECT id, player_id, game_id, joined, ready, red, yellow, green, blue, missed FROM player_games
WHERE game_id = ?"
  #(sql, [dev.ParamString(game_id)], get_player_games_with_game_id_decoder())
}

pub fn get_player_games_with_game_id_decoder() -> decode.Decoder(
  GetPlayerGamesWithGameId,
) {
  use id <- decode.field(0, decode.string)
  use player_id <- decode.field(1, decode.string)
  use game_id <- decode.field(2, decode.string)
  use joined <- decode.field(3, decode.int)
  use ready <- decode.field(4, dev.bool_decoder())
  use red <- decode.field(5, decode.int)
  use yellow <- decode.field(6, decode.int)
  use green <- decode.field(7, decode.int)
  use blue <- decode.field(8, decode.int)
  use missed <- decode.field(9, decode.int)
  decode.success(GetPlayerGamesWithGameId(
    id:,
    player_id:,
    game_id:,
    joined:,
    ready:,
    red:,
    yellow:,
    green:,
    blue:,
    missed:,
  ))
}
