//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub type AddPlayer {
  AddPlayer(id: String, name: Option(String))
}

pub fn add_player(id id: String, name name: Option(String)) {
  let sql =
    "INSERT INTO players (
	id, name
) VALUES (
	?, ?
)
RETURNING id, name"
  #(
    sql,
    [
      dev.ParamString(id),
      dev.ParamNullable(option.map(name, fn(v) { dev.ParamString(v) })),
    ],
    add_player_decoder(),
  )
}

pub fn add_player_decoder() -> decode.Decoder(AddPlayer) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.optional(decode.string))
  decode.success(AddPlayer(id:, name:))
}

pub type GetPlayer {
  GetPlayer(id: String, name: Option(String))
}

pub fn get_player(id id: String) {
  let sql =
    "SELECT id, name FROM players
WHERE id = ?"
  #(sql, [dev.ParamString(id)], get_player_decoder())
}

pub fn get_player_decoder() -> decode.Decoder(GetPlayer) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.optional(decode.string))
  decode.success(GetPlayer(id:, name:))
}

pub type UpdatePlayer {
  UpdatePlayer(id: String, name: Option(String))
}

pub fn update_player(name name: Option(String), id id: String) {
  let sql =
    "UPDATE players
SET name = ?
WHERE id = ?
RETURNING id, name"
  #(
    sql,
    [
      dev.ParamNullable(option.map(name, fn(v) { dev.ParamString(v) })),
      dev.ParamString(id),
    ],
    update_player_decoder(),
  )
}

pub fn update_player_decoder() -> decode.Decoder(UpdatePlayer) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.optional(decode.string))
  decode.success(UpdatePlayer(id:, name:))
}

pub type AddGame {
  AddGame(id: String, code: String, status: Option(String))
}

pub fn add_game(id id: String, code code: String) {
  let sql =
    "INSERT INTO games (
	id, code 
) VALUES (
	?, ?
)
RETURNING id, code, status"
  #(sql, [dev.ParamString(id), dev.ParamString(code)], add_game_decoder())
}

pub fn add_game_decoder() -> decode.Decoder(AddGame) {
  use id <- decode.field(0, decode.string)
  use code <- decode.field(1, decode.string)
  use status <- decode.field(2, decode.optional(decode.string))
  decode.success(AddGame(id:, code:, status:))
}

pub type GetGames {
  GetGames(id: String, code: String, status: Option(String))
}

pub fn get_games() {
  let sql = "SELECT id, code, status FROM games"
  #(sql, [], get_games_decoder())
}

pub fn get_games_decoder() -> decode.Decoder(GetGames) {
  use id <- decode.field(0, decode.string)
  use code <- decode.field(1, decode.string)
  use status <- decode.field(2, decode.optional(decode.string))
  decode.success(GetGames(id:, code:, status:))
}

pub type GetGameWithCode {
  GetGameWithCode(id: String, code: String, status: Option(String))
}

pub fn get_game_with_code(code code: String) {
  let sql =
    "SELECT id, code, status FROM games
WHERE code = ?"
  #(sql, [dev.ParamString(code)], get_game_with_code_decoder())
}

pub fn get_game_with_code_decoder() -> decode.Decoder(GetGameWithCode) {
  use id <- decode.field(0, decode.string)
  use code <- decode.field(1, decode.string)
  use status <- decode.field(2, decode.optional(decode.string))
  decode.success(GetGameWithCode(id:, code:, status:))
}

pub type UpdateGame {
  UpdateGame(id: String, code: String, status: Option(String))
}

pub fn update_game(status status: Option(String), id id: String) {
  let sql =
    "UPDATE games
SET status = ?
WHERE id = ?
RETURNING id, code, status"
  #(
    sql,
    [
      dev.ParamNullable(option.map(status, fn(v) { dev.ParamString(v) })),
      dev.ParamString(id),
    ],
    update_game_decoder(),
  )
}

pub fn update_game_decoder() -> decode.Decoder(UpdateGame) {
  use id <- decode.field(0, decode.string)
  use code <- decode.field(1, decode.string)
  use status <- decode.field(2, decode.optional(decode.string))
  decode.success(UpdateGame(id:, code:, status:))
}

pub type AddPlayerGame {
  AddPlayerGame(
    id: Int,
    player_id: String,
    game_id: String,
    joined: Option(decode.Dynamic),
    ready: Option(Int),
    red: Option(Int),
    yellow: Option(Int),
    green: Option(Int),
    blue: Option(Int),
    missed: Option(Int),
  )
}

pub fn add_player_game(player_id player_id: String, game_id game_id: String) {
  let sql =
    "INSERT INTO player_game (
	player_id, game_id
) VALUES (
	?, ?
)
RETURNING id, player_id, game_id, joined, ready, red, yellow, green, blue, missed"
  #(
    sql,
    [dev.ParamString(player_id), dev.ParamString(game_id)],
    add_player_game_decoder(),
  )
}

pub fn add_player_game_decoder() -> decode.Decoder(AddPlayerGame) {
  use id <- decode.field(0, decode.int)
  use player_id <- decode.field(1, decode.string)
  use game_id <- decode.field(2, decode.string)
  use joined <- decode.field(3, decode.optional(decode.dynamic))
  use ready <- decode.field(4, decode.optional(decode.int))
  use red <- decode.field(5, decode.optional(decode.int))
  use yellow <- decode.field(6, decode.optional(decode.int))
  use green <- decode.field(7, decode.optional(decode.int))
  use blue <- decode.field(8, decode.optional(decode.int))
  use missed <- decode.field(9, decode.optional(decode.int))
  decode.success(AddPlayerGame(
    id:,
    player_id:,
    game_id:,
    joined:,
    ready:,
    red:,
    yellow:,
    green:,
    blue:,
    missed:,
  ))
}

pub type GetPlayerGame {
  GetPlayerGame(
    id: Int,
    player_id: String,
    game_id: String,
    joined: Option(decode.Dynamic),
    ready: Option(Int),
    red: Option(Int),
    yellow: Option(Int),
    green: Option(Int),
    blue: Option(Int),
    missed: Option(Int),
  )
}

pub fn get_player_game(player_id player_id: String, game_id game_id: String) {
  let sql =
    "SELECT id, player_id, game_id, joined, ready, red, yellow, green, blue, missed FROM player_game
WHERE player_id = ? AND game_id = ?"
  #(
    sql,
    [dev.ParamString(player_id), dev.ParamString(game_id)],
    get_player_game_decoder(),
  )
}

pub fn get_player_game_decoder() -> decode.Decoder(GetPlayerGame) {
  use id <- decode.field(0, decode.int)
  use player_id <- decode.field(1, decode.string)
  use game_id <- decode.field(2, decode.string)
  use joined <- decode.field(3, decode.optional(decode.dynamic))
  use ready <- decode.field(4, decode.optional(decode.int))
  use red <- decode.field(5, decode.optional(decode.int))
  use yellow <- decode.field(6, decode.optional(decode.int))
  use green <- decode.field(7, decode.optional(decode.int))
  use blue <- decode.field(8, decode.optional(decode.int))
  use missed <- decode.field(9, decode.optional(decode.int))
  decode.success(GetPlayerGame(
    id:,
    player_id:,
    game_id:,
    joined:,
    ready:,
    red:,
    yellow:,
    green:,
    blue:,
    missed:,
  ))
}

pub type UpdatePlayerGame {
  UpdatePlayerGame(
    id: Int,
    player_id: String,
    game_id: String,
    joined: Option(decode.Dynamic),
    ready: Option(Int),
    red: Option(Int),
    yellow: Option(Int),
    green: Option(Int),
    blue: Option(Int),
    missed: Option(Int),
  )
}

pub fn update_player_game(
  ready ready: Option(Int),
  red red: Option(Int),
  yellow yellow: Option(Int),
  green green: Option(Int),
  blue blue: Option(Int),
  missed missed: Option(Int),
  id id: Int,
) {
  let sql =
    "UPDATE player_game
SET ready = ?,
red = ?,
yellow = ?,
green = ?,
blue = ?,
missed = ?
WHERE id = ?
RETURNING id, player_id, game_id, joined, ready, red, yellow, green, blue, missed"
  #(
    sql,
    [
      dev.ParamNullable(option.map(ready, fn(v) { dev.ParamInt(v) })),
      dev.ParamNullable(option.map(red, fn(v) { dev.ParamInt(v) })),
      dev.ParamNullable(option.map(yellow, fn(v) { dev.ParamInt(v) })),
      dev.ParamNullable(option.map(green, fn(v) { dev.ParamInt(v) })),
      dev.ParamNullable(option.map(blue, fn(v) { dev.ParamInt(v) })),
      dev.ParamNullable(option.map(missed, fn(v) { dev.ParamInt(v) })),
      dev.ParamInt(id),
    ],
    update_player_game_decoder(),
  )
}

pub fn update_player_game_decoder() -> decode.Decoder(UpdatePlayerGame) {
  use id <- decode.field(0, decode.int)
  use player_id <- decode.field(1, decode.string)
  use game_id <- decode.field(2, decode.string)
  use joined <- decode.field(3, decode.optional(decode.dynamic))
  use ready <- decode.field(4, decode.optional(decode.int))
  use red <- decode.field(5, decode.optional(decode.int))
  use yellow <- decode.field(6, decode.optional(decode.int))
  use green <- decode.field(7, decode.optional(decode.int))
  use blue <- decode.field(8, decode.optional(decode.int))
  use missed <- decode.field(9, decode.optional(decode.int))
  decode.success(UpdatePlayerGame(
    id:,
    player_id:,
    game_id:,
    joined:,
    ready:,
    red:,
    yellow:,
    green:,
    blue:,
    missed:,
  ))
}
